# --- .github/workflows/run_research.yml (FINAL ROBUST VERSION) ---

name: Run Helios Research Agent

on:
  repository_dispatch:
    types: [run-helios-research]

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      # We must check out the repository to get access to our script files
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # --- NEW STEP ADDED HERE ---
      # This step gives our script the necessary permissions to run.
      - name: Make script executable
        run: chmod +x .github/entrypoint.sh

      - name: Run Research Script
        # Securely pass the secret API key to the script's environment
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        # This simple, single line executes our script.
        # It passes the topic data as a command-line argument.
        run: .github/entrypoint.sh "${{ github.event.client_payload.topic }}"
